---

- name: Adding primary group
  ansible.builtin.group:
    name: "{{ users_group.name }}"
    gid: "{{ users_group.gid | default(omit) }}"
    state: present
  when: users_group is defined and users_group | length > 0

- name: Adding secondary groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"

- name: Configure users
  ansible.builtin.include_tasks: manage_user.yml
  with_items: "{{ users }}"
  loop_control:
    loop_var: user

- name: Removing users
  ansible.builtin.user:
    name: "{{ item.username if item.username is defined else item }}"
    state: absent
    remove: "{{ item.remove if item.remove is defined else omit }}"
  with_items: "{{ users_remove }}"
